### ISSUE TITLE
More error handling around client smooch init

### ISSUE THREAD

**Issue by claytantor** [claytantor/apiai-smooch-docker#1]
Looks like init handling is weak.

```
Running on http://0.0.0.0:8079/ (Press CTRL+C to quit)
HTTP Error 401: Unauthorized
[2017-01-03 16:07:47,295] ERROR in app: Exception on /hc [GET]
Traceback (most recent call last):
 File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
   response = self.full_dispatch_request()
 File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1634, in full_dispatch_request
   self.try_trigger_before_first_request_functions()
 File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1660, in try_trigger_before_first_request_functions
   func()
 File "./application.py", line 53, in init_smooch
   for hook in webhooks_available['webhooks']:
KeyError: 'webhooks'
172.17.0.1 - - [03/Jan/2017 16:07:47] "GET /hc HTTP/1.1" 500 -
```
ok so I see one thing...

are you sure you have this configured correctly?

```
 jwt = smooch.get_jwt(app.config["SMOOCH_KEY_ID"], app.config['SMOOCH_SECRET'])
```

it seems to not be getting your smooch webhooks
I probably should put more error handling around that.

**Comment by phangs** [comment]
![image](https://cloud.githubusercontent.com/assets/3249866/24745376/16ba2da2-1ae8-11e7-9944-88f61403635a.png)

when using parameters(slot filling in api.ai)
then
